# The google app engine configuration file.

entrypoint: bundle exec rails s -e production
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: 312a2e2b1f5ffe17a27ac438cc823077854c2fcbf2089acb6f7fb1ebea645ff4b8cb92b01878490d2583cb6f1dbfe632c2a36fb546189f66fee21458f0e1ef52

beta_settings:
  cloud_sql_instances: conductive-air-262908:us-central1:optunadb
