# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql2
  pool: 5
  encoding: utf8
  reconnect: false
  host: 35.226.18.113
  username: railsuser
  password: s1S@2i4T6zgfD8aq
  database: optunaexplorerdb_development
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  pool: 5
  encoding: utf8
  reconnect: false
  host: 35.226.18.113
  username: railsuser
  password: s1S@2i4T6zgfD8aq
  database: optunaexplorerdb_test
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  pool: 5
  encoding: utf8
  reconnect: false
  host: 35.226.18.113
  username: railsuser
  password: s1S@2i4T6zgfD8aq
  database: optunaexplorerdb_production
  socket: /tmp/mysql.sock
