name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - name: Install dependencies
        run: |
          sudo apt install -y libsqlite3-dev build-essential ufw
          gem install bundler
          bundle install --without production
          yarn install
          sudo ufw default allow incoming
          sudo ufw default allow outgoing
          sudo ufw enable
      - name: Cucumber Tests
        run: cucumber
      - name: RSpec Tests
        run: rspec