name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup System
        run: sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - name: Install dependencies
        run: |
          sudo apt install -y install libsqlite3-dev build-essential
          gem install bundler
          bundle install --without production
          yarn install
      - name: Cucumber Tests
        run: cucumber